export const SUPABASE_URL = 'https://kpqfszrlbuykuiupcmtw.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwcWZzenJsYnV5a3VpdXBjbXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2MTM0ODgsImV4cCI6MjA5NzE4OTQ4OH0.NdUsPEC7QTKZWdO14ciNDpwcOolXWoiCwpzoYz2ZDe0';
